### ISSUE TITLE
Beacons with speed modules also boost productivity?

### ISSUE THREAD

**Issue by RomashkinAndrew** [modded-factorio/bobsmods#116]
If one builds an production building with productivity modules and surrounds it with beacons with speed modules - turns out that one can achieve not just immense speeds, but also immense productivity. It is most noticeable for fast-building recipes like science packs and intermediaries:
![1](https://github.com/modded-factorio/bobsmods/assets/29290085/130be187-d74a-4737-b96b-3253a3697385)
![2](https://github.com/modded-factorio/bobsmods/assets/29290085/3aac8091-de89-422c-95c6-c6ecd0e22bab)
![3](https://github.com/modded-factorio/bobsmods/assets/29290085/f9379de2-12f7-4631-a358-10661f28829f)
![4](https://github.com/modded-factorio/bobsmods/assets/29290085/c507f124-c781-4be6-84d1-fc5397e2d727)

In combination with Angel's mod pack, it allows to create setups, which basically give player infinite resources:
![5](https://github.com/modded-factorio/bobsmods/assets/29290085/0af0de28-8f3e-45c7-b96f-8926dc450b9d)
![6](https://github.com/modded-factorio/bobsmods/assets/29290085/801da6d6-8261-45fd-aa76-704ec144ed76)

Is it a bug or an intended behavior? IMO, it's not expected to get productivity boost from speed modules.

**Comment by KiwiHawk** [comment]
This is known behaviour. Personally, I call this a base game bug. It was reported ages ago but the devs decided not to fix it for some reason.

https://forums.factorio.com/viewtopic.php?f=58&t=72618

The game has hard limit of one recipe completion per tick. Any additional speed modules past this point will have no effect on recipe speed. However, productivity is calculated as if this limit does not exist.

**Comment by RomashkinAndrew** [comment]
That's unfortunate. That means if UPS drops - productivity will boost even more?

**Comment by KiwiHawk** [comment]
No, UPS will have no effect on this. This is based on game ticks, not on real time.

60 UPS means 60 Updates Per Second. Aka 60 ticks per second.
