### ISSUE TITLE
Burner Power Generator has Same Usage Priority as Steam Engine

### ISSUE THREAD

**Issue by Recon419A** [modded-factorio/bobsmods#118]
Mods Enabled: Angel's, Bob's (except Personal Equipment and Vehicle Equipment)

Both the Burner Generator and Steam Engine have a usage priority of three. This means that when both are fueled, the burner generators balance distribution with the steam engines, when it would be "better" for the steam engines to take over entirely, with the burners only as a backup (based on how various power generation methods usually do prioritization).

**Comment by KiwiHawk** [comment]
Using the circuit network, you can prioritize power production as you like. We have a very limited number of power priorities to work with so I'm not interested in changing this sorry.
