### ISSUE TITLE
Plutonium Synthesis Research Locked

### ISSUE THREAD

**Issue by kidol1** [modded-factorio/bobsmods#119]
I cant reserach plutonium-synthesis. I have unlock plutonium-based power system and i cant go achad.
![Zrzut ekranu (48)](https://github.com/modded-factorio/bobsmods/assets/134531248/69b193fc-f508-4595-ba0f-3b80e6f878c1)
[ANGEL BOBS 1 tessto.zip](https://github.com/modded-factorio/bobsmods/files/11556650/ANGEL.BOBS.1.tessto.zip)

**Comment by KiwiHawk** [comment]
Issue can be reproduced with just the following mods:
- Bob's Metals, Chemicals and Intermediates mod
- Nuclear Fuel

Nuclear Fuel mod hides Kovarex enrichment process tech
