### ISSUE TITLE
Tech prerequisites

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#120]
### Fix unit test failures
- Add tech to unlock gem ore to raw gem recipes
  - Currently unlocked from start
  - Add tech Gem processing 3
  - Move existing recipes up a tech
  - Automation as a prerequisite
  - Notify Artisanal Reskins of the change
- Add a tech to unlock resin and rubber
  - Automation as a prerequisite
  - Tech name: Wood processing
- Make Automation a prerequisite for the following techs, either directly or indirectly
  - Engine
  - Silicon processing
- Make Alloy processing a prerequisite for the following techs (for Metal mixing furnace)
  - Cobalt processing
  - Tungsten processing
  - Zinc processing
- Add production science pack (purple) as a prerequisite for Repair pack 5
- Bob's Logistics moves Lubricant to green science. There is no vanilla way of making heavy oil at this stage
  - Add recipe `bob-oil-processing` in Bob's Logistics (as well as MCI and Electronics)
  - Move solid fuel recipes to Flammables to use up excess oil products

**Comment by LovelySanta** [comment]
https://github.com/Arch666Angel/mods/pull/911 is tested and merged.
