### ISSUE TITLE
Missing Pipe recipes

### ISSUE THREAD

**Issue by SGZ-Creations** [modded-factorio/bobsmods#121]
Copper pipe recipe can't be unlocked.

Bob's Logistics: SE, K2, BZ,
[1.1.82-1 K2_SE_BZ.zip](https://github.com/modded-factorio/bobsmods/files/11624509/1.1.82-1.K2_SE_BZ.zip)

**Comment by KiwiHawk** [comment]
![image](https://github.com/modded-factorio/bobsmods/assets/59639/c0ecf5e9-02e7-4090-a5d5-ecdd2608e836)

What does SE-Recipe-Tweaker mod do? It's in the save but not on the mod portal. I got the following when loading without it:

![image](https://github.com/modded-factorio/bobsmods/assets/59639/234a9b83-38dd-4f25-95d0-a6e00b7ac4d2)

**Comment by KiwiHawk** [comment]
Minimum mod list:
- AAI Industry
- Bob's Functions Library mod
- Bob's Logistics mod
- Factorio Library
- Krastorio 2
- Krastorio 2 Assets

**Comment by SGZ-Creations** [comment]
it a mod by me and ((immow)person on discord) made a mod that was letting us cunstomize some recipes regarding SE only. tho i personly made it so i required a custom version of SE as i also disabled the a section within SE to remove the stack size limit of rocket without causing a crash.

modified to use in save: without any crash as far i know.
[space-exploration_0.6.108.zip](https://github.com/modded-factorio/bobsmods/files/11740782/space-exploration_0.6.108.zip)
[SE-Recipe-Tweaker_0.0.4.zip](https://github.com/modded-factorio/bobsmods/files/11740792/SE-Recipe-Tweaker_0.0.4.zip)

updated version to reduce crashes should some forget to modify the SE mod (UNTESTED)
[SE-Recipe-Tweaker_0.0.5.zip](https://github.com/modded-factorio/bobsmods/files/11740819/SE-Recipe-Tweaker_0.0.5.zip)

**Comment by SGZ-Creations** [comment]
I personly working on publishing that mod soon.

**Comment by KiwiHawk** [comment]
Logged this to hopefully be fixed in AAI Industries. https://github.com/EarendelDevelopers/factorio-mods/issues/303

**Comment by KiwiHawk** [comment]
Fixed in AAI Industry 0.5.21
