### ISSUE TITLE
Personal fusion reactor does not follow alien science pack logic

### ISSUE THREAD

**Issue by LovelySanta** [modded-factorio/bobsmods#124]
This report was created with the dev branch at commit https://github.com/modded-factorio/bobsmods/commit/992cd7cff5cd55f16893f08bdd717ba90eaeb3f6. Listed all bobs mods, looking at alien science research:

* `fusion-reactor-equipment-3` (technology) is researched with blue and orange alien science packs, however the `fusion-reactor-equipment-3` (equipment) takes yellow and purple artifacts.

* `fusion-reactor-equipment-4` (technology) is researched with yellow and purple alien science packs, however the `fusion-reactor-equipment-4` (equipment) takes green and red artifacts.

To follow the logic further:
* `fusion-reactor-equipment-2` (technology) is researched with regular science packs (yellow), however the `fusion-reactor-equipment-2` (equipment) takes blue and orange artifacts, move this to alien research instead of utility science pack?

**Comment by KiwiHawk** [comment]
Additional related issue: Personal laser defence equipment 6 takes red and green artifacts but doesn't use alien science packs.
