### ISSUE TITLE
Support "slim" inserters

### ISSUE THREAD

**Issue by kuxynator** [modded-factorio/bobsmods#126]
*Since in the [mod portal](https://mods.factorio.com/mod/bobinserters/discussion/649d049a25b24a5f07822ea3) are already unanswered questions older than 17 days I write here again.*
***

**Would you like to support "slim" inserters?**
This are inserters like in Dyson Sphere Program (DSP)
Technical based on "vanilla" inserter but with a height of 0 instead of 1, so the offset position are 0.5 tiles shorter.
The concept states that these inserters should not be able to change the angle, except fine posititioning of drop location. so the UI should be adapted.
![https://imgur.com/hH5XAJz](https://i.imgur.com/hH5XAJz.png)

A functional implementation of these "slim" inserters can be found in [Arrow Inserter](https://mods.factorio.com/mod/arrow-inserter) from Bleb1k which had this idea (and of which I am a contributor)

Thx and best regards
Kux

P.S. I already have a working **local only** version with bobinserters support ready, these are minimal changes to the code. only the customized UI is still missing. 
![](https://assets-mod.factorio.com/assets/ext/beabcc3897568d14007b1ff77745ecdd6e82c3db81a1337bb734a57999972b6c.png)

**Comment by KiwiHawk** [comment]
I'm open to the idea. Ideally it would be based on the prototypes though, rather than a specific mod.

**Comment by kuxynator** [comment]
yes, my local changes does not relay on  a specific mod, I use tile_width and tile_hight, to recalculate the positions.
may I make a public fork so you can look at my changes?

**Comment by KiwiHawk** [comment]
Sure. Fork and create a Pull Request. Thanks!

**Comment by kuxynator** [comment]
PR for the first part. https://github.com/modded-factorio/bobsmods/pull/131/

**Comment by KiwiHawk** [comment]
I'll put reviewing this on my to-do list 

You say "first part". What else is not yet implemented?

**Comment by kuxynator** [comment]
the "first part" allows full configuration for all inserter types.
But the arrow-inserter should have an interface like shown above, i.e. not all positions are available.
This "second part" will implement the limited configuration specially for arrow-inserter. But I have no clue (yet) how to implement this universally.

**Comment by kuxynator** [comment]
when do you think this will be merged?

**Comment by KiwiHawk** [comment]
Some time before the next release 🤷‍♂️
I'd like to spend some time figuring out how the second part could be implemented. I'm guessing via the remote interface.

**Comment by kuxynator** [comment]
yes, remote interface. 
befor you update the configuration  GUI you could raise an event ( callback a registered mod) including
- the entity
the return value contains the configuration for the GUI, including 
- a cancel flag, true indicates not to show the configuration GUI (same as blaklisted but situation dependent)
- a matrix with generally allowed positions
