### ISSUE TITLE
Bob's Function library mod removes Vitamelange core fragments from Biological Science 4.

### ISSUE THREAD

**Issue by CaitSith2** [modded-factorio/bobsmods#127]
![image](https://github.com/modded-factorio/bobsmods/assets/79097/c2d22fed-0c9b-4201-bcf6-9930a260da93)
![image](https://github.com/modded-factorio/bobsmods/assets/79097/f96a2427-07a0-4a8a-a9b5-a7334d68ed21)

3.788 Loading mod boblibrary 1.1.6 (data-final-fixes.lua)
   3.789 Script @__boblibrary__/technology-functions.lua:990: Running technology prerequisite cleanup...
   3.808 Script @__boblibrary__/recipe-functions.lua:640: Running recipe ingredients cleanup...
   3.845 Script @__boblibrary__/item-functions.lua:124: stack traceback:
	__boblibrary__/item-functions.lua:124: in function 'ingredient'
	__boblibrary__/recipe-functions.lua:594: in function 'duplicate_ingredient_check'
	__boblibrary__/recipe-functions.lua:616: in function 'duplicate_ingredient_check_full'
	__boblibrary__/recipe-functions.lua:642: in function 'ingredients_cleanup'
	__boblibrary__/data-final-fixes.lua:5: in main chunk
   3.845 Script @__boblibrary__/error-functions.lua:108: Ingredient.name not a valid item of any type.
   3.845 Script @__boblibrary__/recipe-functions.lua:605: Invalid item found on recipe se-biological-science-pack-4.

**Comment by KiwiHawk** [comment]
As a temporary workaround, disable Bob's Library setting `Enable Recipe ingredients cleanup`.

**Comment by CaitSith2** [comment]
Looked into it a bit further, and found that the core fragment item is defined in data-final-fixes,  while the recipe for Biological Science Pack 4 is defined in data.  (Space exploration calls them phase 1 and phase 3 respectively.   (phase 4 in space exploration is data-final-fixes in space-exploration-post-process.)).

As a result, in the current implementation, this will ALWAYS kill the core-fragment requirement since recipe cleanup happens in phase 1.

**Comment by CaitSith2** [comment]
Damn,  looks like its up to space exploration to fix this issue as there are circular dependency issues if bobslibrary attempts to include space-exploration as optional, to try and get the core-fragment to be defined before the cleanup happens.

**Comment by CaitSith2** [comment]
Reported it as a bug to space exploration as they will have to be the ones to apply a compatibility fix for it.

**Comment by KiwiHawk** [comment]
Fixed in Space Exploration 0.6.109
