### ISSUE TITLE
Use not-in-made-in flag to reduce Made In list sizes

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#169]
Bob's mods can make the Made In list part of a recipe screen excessively long. This could be cleaned up quite a bit if we use the not-in-made-in flag to reduce the number of entities that show up in the list. I would suggest creating a setting in Bob's Assembly to show only the first two Assembling machines and Electronics machines, since their first tiers have the difference of not being able to use fluids, and only one of the rest of the groups. So, Stone Furnace, Electric Furnace, Chemical Furnace, Mixing Furnace, Chem plant 1, Oil refinery 1, Centrifuge 1, Electrolyser 1, and so on. For Bob's Classes, a setting with three options would probably be good. One that keeps all of the character classes in the list, one that removes all of them, and one that removes all of them except for the basic and miner characters.

![Untitled](https://github.com/modded-factorio/bobsmods/assets/108201496/5576f073-4a2a-482f-8189-8d619cc7132d)

**Comment by KiwiHawk** [comment]
I dislike settings. I believe they should be avoided wherever possible. They generally mean that neither option is "correct".

I do agree that the made in list is unwieldy. I'd definitely be happy with hiding all the characters from this list.

**Comment by Qatavin** [comment]
I can see that viewpoint, but in this case it's not something that really affects gameplay, so it's not so much a matter of correct or incorrect as it is a personal preference for how much cleanup you want.
