### ISSUE TITLE
Equipment Tiers

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#181]
# Portable Solar Panels

![image](https://github.com/modded-factorio/bobsmods/assets/59639/fe8642cf-930c-49c1-aba1-50d80a93b279)

Increase tech tier of T2, T3, and T4

# Energy Shield

![image](https://github.com/modded-factorio/bobsmods/assets/59639/dc6bec43-ce0a-4fd9-a9f2-ed2618dd5b83)

- Make T1 use Green Circuits
- Make T2 use Red Circuits
- Add Prod Module 1 to T2

# Other
Apply similar changes to the following:

- Personal Battery
- Night vision
- Personal Laser Defence
- Exoskeleton
- Belt Immunity
- Power armour

**Comment by mecejide** [comment]
Is Bob’s Vehicle equipment going to remain unchanged?

**Comment by KiwiHawk** [comment]
#180 and #184 affected Bob's Vehicle Equipment. I'm undecided about applying the changes from this issue to vehicle equipment.
