### ISSUE TITLE
Nuclear reactor pipes color update

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#186]
It looks like when tier 4 heat pipes were created, we didn't update the graphics on the nuclear reactors to match. Nuclear reactors 1, 2, and 3 now use heat pipes 2, 3, and 4 in their recipes, but still have graphics for heat pipes 1, 2, and 3. The fix should be easy enough; the graphics can just be swapped to the reactor that's one tier lower. However, new graphics will need to be created for nuclear reactor 3. That's easy enough as well. I could take care of it myself, but it would be helpful to know what was done to create the tier 4 pipe graphics.

Alternatively, we could create new graphics for tier 2 pipes and tier 1 nuclear reactors. For quick reference, here are the ingredients for heat pipes:

Tier 1: copper, steel (heat source 1)
Tier 2: aluminium, invar (heat source 2, nuclear reactor 1)
Tier 3: silver, titanium (nuclear reactor 2)
Tier 4: gold, copper-tungsten (nuclear reactor 3)

![reactor-color-disconnect](https://github.com/modded-factorio/bobsmods/assets/108201496/49dffc75-6639-4476-8af7-2928837fbbad)

The white and gold-colored bases could be kept on nuclear reactors 2 and 3, and we could switch heat pipes 3 and 4 respectively to use the same coloration. New graphics could be created for heat pipes 2 and nuclear reactor 1, perhaps something in a duller gray to represent aluminium and invar. This way, the gold-colored graphics would be given to the pipes that are made of gold, and the white graphics would belong to the pipes that use silver and titanium.

Also, did the burner heat source buildings get bigger at some point? I could have sworn you used to be able to see more of the heat pipes underneath them than this.

**Comment by KiwiHawk** [comment]
@atburghardt made the PR to update the heat pipes. Any chance you two can work together on this one?

https://github.com/modded-factorio/bobsmods/pull/95

**Comment by Qatavin** [comment]
![new heat pipe 2 test](https://github.com/modded-factorio/bobsmods/assets/108201496/22ca6bf0-5a64-4b6c-8854-982a70ec4d18)

I would propose this for new aluminium-invar heat pipe 2/nuclear reactor 1/heat source 2 graphics. I've only edited a few so far. Together with this, my recommendation is to use the white pipe graphics for heat pipe 3 and the gold pipe graphics for heat pipe 4.

**Comment by KiwiHawk** [comment]
Burner heat sources, fluid burning heat sources, and nuclear reactors all look good! Heat exchangers don't match their ingredient heat pipe color though.

![image](https://github.com/user-attachments/assets/85c135b1-afec-4158-933a-96dd7761d1ef)

**Comment by Qatavin** [comment]
I believe that's always been the case, which means fixing it will probably take a couple minutes. I'll look into it in a little while, once I'm done with what I'm currently doing.
