### ISSUE TITLE
Gear Wheel Cost

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#190]
Iron Gear Wheels cost 2 Iron plates. Other gear wheels only cost a single iron plate. Should this be increased to two?

**Comment by Qatavin** [comment]
Or Iron Gears could be made to cost 1. They should be the same, but I'm not sure which way would be better to go for. I'd lean towards reducing the cost, though. Doubling the price of other gears would add up to millions of units of material. For Titanium Gears in particular, that seems like it would cause a substantial issue in terms of Sodium Hydroxide glut.

**Comment by KiwiHawk** [comment]
I think I prefer increasing the cost rather than reducing iron. Having a change of density (either up or down) introduces potentially interesting logistics design decisions. So I prefer to avoid 1:1 recipes.

You are correct that this would be a substantial increase in cost to a lot of things! So it should be paired with recipes being updated to use fewer gears to at least partially offset the cost. It's more work but I think will give us a better outcome.

**Comment by KiwiHawk** [comment]
I have a separate issue logged about having a sink for sodium hydroxide. For when science isn't sufficient to consume it all.

https://github.com/modded-factorio/bobsmods/issues/145

**Comment by Qatavin** [comment]
Could reduce gears in:
Belts from 4 to 2
Splitters from 14 to 10
Assembling machines, electronics machines, chemical plants from 5 to 4 and do the same for bearings.
Turrets from 10 to 8 (bearings too)
Sniper turrets from 20 to 16 (bearings too)

There are other things that use gears, of course, but these are the big ticket items. For most of the others, I doubt changing their recipes would make much of a dent in the grand scheme of things. And for some, I think it would be fine to give them a relative price increase. Underground belts in particular are probably too cheap after the yellow tier currently. Perhaps we could make their recipes automatically adjust according to what the underground belt distance settings say.
