### ISSUE TITLE
Bob's Inserter crash when opening Inserter Preview

### ISSUE THREAD

**Issue by Harvus00** [modded-factorio/bobsmods#204]
The mod Bob's Adjustable Inserters mod (1.3.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event bobinserters::bob-inserter-open-gui (ID 214)
bool expected, got string
stack traceback:
	[C]: in function '__newindex'
	__bobinserters__/control.lua:1485: in function 'open_gui'
	__bobinserters__/control.lua:479: in function <__bobinserters__/control.lua:469>
[_autosave1.zip](https://github.com/user-attachments/files/17533969/_autosave1.zip)
[factorio-current.log](https://github.com/user-attachments/files/17533971/factorio-current.log)

**Comment by KiwiHawk** [comment]
Fixed for v1.3.1
