### ISSUE TITLE
2.0 BobLibrary

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#208]
item-functions:

- [x] function bobmods.lib.item.ingredient:
Tries to do "log(item.name)" and "bobmods.lib.error.ingredient(item)" when "item" is nil.
Should be "log(inputs.name)" and "bobmods.lib.error.ingredient(inputs)"
Alternatively, something like the following may be more helpful.
`if not inputs.name then log("Ingredient name missing. Input may be in deprecated shorthand format.") end`

function bobmods.lib.item.result has a similar issue.

- [x] function bobmods.lib.item.get_type
In the data.raw.fluid section, always sets item_type = type_name when type_name will always be nil
Should be item_type = "fluid"

error-functions:

- [x] function bobmods.lib.error.result:
Tries to do "if result.amount then" and other conditionals when "result" can be nil
Can be solved by folding these conditionals into the if-then-elseif that starts with "if result == nil then"

module-functions:

- [x] bobmods.lib.module.add_productivity_limitation
I guess we could do something cheeky like repurpose this to add allow_productivity to recipes instead, but it's probably best to just remove it and all associated files and lists once we're done using them to add the parameter to recipes manually.

technology-functions:

- [x] function bobmods.lib.tech.prerequisite_cleanup:
This function and the setting associated with it are now redundant for players, since the base game does the same thing on its own. However, for mod developers, there is definitely still some value in it, since it can be used to generate a log of redundant prerequisites to allow for cleanup. I suggest switching the setting to be off by default, removing the comment marks on the line "log("removed " .. prerequisite .. " from " .. technology_name)" and changing the setting description to explain that its new purpose.

**Comment by KiwiHawk** [comment]
I've removed the prerequisites check entirely. I'd rather not have debug functions in the library. If it is useful, it can always be recreated as a separate mod. Or even added to [Angel's Unit Test mod](https://github.com/Arch666Angel/mods/tree/master/angelsdev-unit-test).

**Comment by Qatavin** [comment]
Spotted an issue with the new functions bobmods.lib.recipe.allow_productivity() and bobmods.lib.recipe.disallow_productivity(). Both are missing their argument. Should be (recipe_name).

**Comment by KiwiHawk** [comment]
Good catch! Thanks. Clearly I tested it thoroughly 🤦‍♂️
