### ISSUE TITLE
2.0 Bob's Electronics

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#215]
For Bob's Electronics, there's almost nothing that needs to be fixed to get it to load. Because of that, I'm kinda jumping ahead and looking into the polishing side of things on this one, so I might not put together a pull request right away. As far as issues that may need some consideration:

- Vanilla has now moved "electronics" to the very top of the tech tree, above even "automation science pack", and with an unlock for the lab. I think it's going to be necessary to give the basic circuit board to this tech (it's the one that's unlocked by making copper plates, so no worries about making it unobtainable) and create a new "bob-electronics" tech to assign the yellow circuit board to.
- As we've all noticed, in vanilla, the techs "advanced-electronics" and "advanced-electronics-2" are now "advanced-circuit" and "processing-unit". It might be a bit annoying, but I think we should probably change "advanced-electronics-3" to "advanced-processing-unit" for the sake of consistency.

**Comment by KiwiHawk** [comment]
Yup, that all makes sense to me.
