### ISSUE TITLE
Power Entity Improvements

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#22]
## Issues
Upgrade planner cannot be used to upgrade Heat Pipes

There is no way of seeing in game the difference between heat pipe tiers

### Current tiers
- **T1** - Max temperature: 750
  - Burner heat source
  - Fluid burning heat source

- **T2** - Max temperature: 875
  - Burner heat source 2
  - Fluid burning heat source 2

- **T3** - Max temperature: 1000
  - Heat pipe
  - Burner heat source 3
  - Fluid burning heat source 3
  - Nuclear reactor

- **T4** - Max temperature: 1250
  - Heat pipe 2
  - Thorium reactor

- **T5** - Max temperature: 1500
  - Heat pipe 3
  - Deuterium reactor

## Suggested Fixes
Make Heat Pipes upgradable
Add max temperature to heat pipe descriptions

Remove Burner Heat Source 3 and Fluid Burning Heat Source 3
Add migration to update removed items / entities / recipes

Add a fourth tier of Heat Pipe and Heat Exchanger

### New Heat Entity Tiers
- **T1** - Max temperature: 750   (Green Science)
  - Burner Heat Source
  - Fluid Burning Heat Source
  - Heat Pipe 1
  - Heat Exchanger 1

- **T2** - Max temperature: 1000  (Blue Science)
  - Burner Heat Source 2
  - Fluid Burning Heat Source 2
  - Nuclear Reactor
  - Heat Pipe 2
  - Heat Exchanger 2

- **T3** - Max temperature: 1250  (Purple Science)
  - Nuclear Reactor 2
  - Heat Pipe 3
  - Heat Exchanger 3

- **T4** - Max temperature: 1500  (Yellow Science)
  - Nuclear Reactor 3
  - Heat Exchanger 3
  - Heat Pipe 4
  - Heat Exchanger 4

### Move power entities up a tier
- Entities
  - Boiler
  - Fluid Burning Boiler
  - Steam Engine
  - Steam Turbine
  - Fluid Burning Generator
  - Hydrazine Generator
- New Tiers
  - T2: Green Science
  - T3: Blue Science
  - T4: Purple Science
  - T5: Yellow Science

**Comment by atburghardt** [comment]
Proposal:

- T0: 
   - 20 Copper
   - 10 Tin

- T1:
   - 20 Bronze
   - 10 Steel
   
Add T0 heat exchanger:
- Boiler 2
- 4 T0 heatpipe 
- color matching ingredients

Add recipes, so you can upgrade heat exchanger from t0->t3 and make them from matching boiler, so boiler 4&5 can be recycled.
