### ISSUE TITLE
How will quality affect bobs for 2.0?

### ISSUE THREAD

**Issue by SKeeneCode** [modded-factorio/bobsmods#227]
Apologies if this question has been posted elsewhere. If so, please close this issue and point me to the answer! I have looked by haven't found anything yet.

Given bobs mods add multiple tiers of most things, this has a heavy overlap with quality and sort of serves the same function.

Does bobs mods intend to balance for quality, with the expectation that players will enable quality with it, or will it ignore quality and stick with its original tiers and let users simply add quality if they choose to?

Thanks for your hard work and time! I cannot wait to play an angels/bobs updated to 2.0 :)

**Comment by KiwiHawk** [comment]
Our first priority is just getting the mods working with 2.0 . Compatibility with Space Age and Quality can come after.

I agree, multiple tiers and quality feels redundant. My current thought is to only allow quality on the final tier.

**Comment by SKeeneCode** [comment]
Thank you for the prompt answer! Selectively allowing quality on the final tiers seems like a fine solution and makes the best of both worlds!

I'll close the issue now - thanks again!
