### ISSUE TITLE
Entity Flipping

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#229]
Check if `graphics_set_flipped` is required (vs just setting [`forced_symmetry`](https://lua-api.factorio.com/latest/prototypes/CraftingMachinePrototype.html#forced_symmetry))

Remove the output fluid box from Electronics Assembling Machines

**Comment by Qatavin** [comment]
Checked this. It seems that yes, forced_symmetry would work as a cleaner alternative to adding an output fluid box. However, graphics_set_flipped is absolutely required in the places where I have applied it.
