### ISSUE TITLE
2.0 Bob's Classes

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#235]
I've got Bob's Classes working, and fortunately there isn't too much that needs to be done with it. However, I think it's worth discussing whether we should look into a major revision for this mod.

I've played runs with all three added character classes, and the basic conclusion I've come to is that if you aren't playing the Balanced class, by far and away the best choice is the Builder. More inventory, extended build range, and double crafting speed, with the only real downside being that it's somewhat slower. Although, as it's current set up, the Builder starts you out without a pistol, which is a fairly serious problem now that pistols are no longer craftable by default (the recipe is still in the game, but is hidden).

In comparison, the Miner has increased mining speed and resource reach distance, and that's basically it. That doesn't help you at all except in the very early game. After that, all it lets you do is unbuild structures a little faster. Woo. It may also have the special ability to smelt and do metal mixing recipes, but there's a big problem with that: those recipes tend to have some of the longer crafting times, so taking advantage of this particular ability is generally not worth your time. On top of that, it's also slower and has less build range.

The Fighter is... fine. It has faster move speed, and that by itself might be reason enough to choose it. It does have a smaller inventory, but an experienced engineer (especially one who rushes logistic bots) can work around that. Reduced build range is always super annoying, though. Overall, the problem I have with it is that it just doesn't feel like to does quite enough to make you into a badass. This is a factory game, not a combat game, so if you're going to have a combat-focused class, it needs to be a little crazy in order to be appealing. Still, at the very least, you can definitely say that the Fighter class accomplishes the goal of changing the way the game plays. I think it could be made into an excellent choice with just a few adjustments, rather than a total rework.

So, in short, I think the Builder class is comparatively OP, the Miner class is critically flawed, and the Fighter class needs some more awesome added.

Here is what I would propose. The only way to fix what the Miner class does is to change it into a new Crafter class and have it steal the Builder class's boost to crafting speed (having both craft faster would seem redundant). Maybe we could also add additional crafting categories to it, like electrolysis, but that would be a minor detail at best. Advanced-crafting, which is only used to make engine units, would be nice to have. One thing I wish we could is add fluid inventory slots to the character, which would be filled from barrels (as a bonus, this would make barreling something you'd want to set up, instead of being largely ignored, as it tends to be otherwise). However, this would be very difficult to accomplish. In return, the Builder class could be changed to move at the same speed as Balanced, and also increase its build distance a bit more - 12 instead of 10 is nice, but wouldn't 15 be so much better? Bottom line, the ultimate idea is to have the Builder be all about making the process of building itself be as smooth and easy as possible, while the Crafter is meant to reduce the running around you do to pick up stacks of intermediates and finished products. Similar, but depending on how you like to play the game, one will be better than the other.

As for the Fighter, there are quite a few options to improve it. ticks_to_stay_in_combat is the parameter that affects how fast a character starts healing, and is normally 600 ticks, or 10 seconds. This could be reduced to 2.5 seconds, so instead of having to hit-and-run enemy bases, you could just attack, attack, attack as long as you can keep dodging most of the Worms' acid. There's also a new parameter for guns_inventory_size, so the Fighter should definitely take advantage of that. Something could also be done to enhance the tool_attack_result for emergency situations - increased damage of around 20 or so, and maybe some pushback. The attack_reaction property also works for characters, so maybe something could be done with that. Additionally, perhaps the Fighter could start out with Modular Armor, along with a few lasers, solar panels, and batteries. This would be far less advantageous than it sounds, by the way. Personal lasers in 2.0 are pretty crappy without any damage or firing speed upgrades.

Here's what I'm thinking, in numbers:

**build_distance/reach_distance/drop_item_distance**
1. Balanced: 10
2. Crafter: 10
3. Builder: **15**
4. Fighter: 8

**crafting_speed**
1. Balanced: 1.5
2. Crafter: **3**
3. Builder: 1
4. Fighter: 0.75

**guns_inventory_size**
1. Balanced: 3
2. Crafter: 2
3. Builder: 2
4. Fighter: **5**

**healing_per_tick**
1. Balanced: 0.18
2. Crafter: 0.1
3. Builder: 0.1
4. Fighter: **0.3**

**ticks_to_stay_in_combat(time to start healing)**
1. Balanced: 480
2. Crafter: 600
3. Builder: 600
4. Fighter: **150**

**inventory_size**
1. Balanced: 80
2. Crafter: **100**
3. Builder: 80
4. Fighter: 60

**loot_pickup_distance**
1. Balanced: 2.5
2. Crafter: 2
3. Builder: 2.5
4. Fighter: **3.5**

**max_health**
1. Balanced: 300
2. Crafter: 200
3. Builder: 200
4. Fighter: **400**

**mining_speed**
1. Balanced: 0.5
2. Crafter: **1**
3. Builder: **1**
4. Fighter: 0.5

**reach_resource_distance**
1. Balanced: 2.7
2. Crafter: 2.7
3. Builder: **3.5**
4. Fighter: **3.5**

**running_speed**
1. Balanced: 0.15
2. Crafter: 0.12
3. Builder: 0.15
4. Fighter: **0.20**

**Light?**
1. Balanced: Normal headlight?
2. Crafter: Weaker headlight?
3. Builder: Weaker headlight?
4. Fighter: Stronger headlight?

**Special**
2. Crafter: Extra crafting_categories - smelting, metal-mixing, advanced-crafting(i.e. engine units)
4. Fighter: Improved tool_attack_result with knockback, starts with modular armor and t1 equipment, attack_reaction?, remove flag breaths-air to give immunity to poison clouds?

**Comment by KiwiHawk** [comment]
I'm not sure about the fluid crafting part. The rest makes sense :-)

**Comment by Qatavin** [comment]
Yeah, the fluid crafting is a pretty wild aspiration.

I've been playing my current mostly vanilla SA run with my new version of the Builder class, and I have to say, it feels really good. I had some concerns about it still being too strong, but it's not too bad. The 15 reach distance is incredibly nice to have, and I hope I won't be spoiled by it. Combat on foot is definitely tougher in the early mid game. The boost to spawner health with evolution really hits fast, and makes it so you can't just run in and snipe them anymore, especially with reduced health and slow regen. But reach distance provides a nice solution to that, letting you lay down a line of turrets much closer to the enemy than you'd otherwise be able to. I do find myself losing a fair number of turrets this way, but if I load them with z instead of going for full stacks, it isn't too painful.


There is one more idea that I've been toying with for a while now, and that is the concept of a Scientist class. One that would be able to craft science packs for free. Now, just on its face, there's a blatantly obvious problem with that. If you can make more of them, you'll totally break the game. As I see it, there are three ways to get around this, all of which effectively limit the number of Scientists to one. The first is to make it so that Scientist can only be picked at game start - but that might make not picking it too much of a disadvantage compared to the other classes, so I don't like it as an option. The second would be to make it so that Scientists require a special item in order to make, and you only ever get a single one of those items at game start if you pick a class other than Scientist, thus making it impossible to ever have more than one - the downside to this being, what if the Scientist dies, and you transfer to another body instead of respawning? Unlikely, but possible.

My preferred option would be to have a database item that spawns in the crashed ship at the start.  The Scientist would use this in the recipes that generate science packs, which would also output the database at the end. As a consequence, only one order of science packs could be stacked at a time, maybe in batches of 20 to 50 or so, nerfing the Scientist's must-have factor in the long run by making them somewhat inconvenient if you decide to start using another character. And if the Scientist dies, the database would be retrievable from their corpse (items currently being used in recipes are returned upon death and appear on the corpse).

They should be strong in the 60SPM stage of the game, but unimpressive in the 600SPM stage. Their purpose is to allow players who know how to plan ahead to push deeper into the tech tree than they normally would, unlocking useful techs like, say, a level of mining productivity before you have the required sci pack in normal production. Or you could simply pick up critical weapon bonuses faster than your limited starting resources would normally allow, to deal with dangerous enemies. The class's stats would be otherwise unimpressive. As I imagine it, this is very much a class for experts. It would be the opposite of the Crafter, pushing players toward automating normal production as much as possible to free up hand crafting for science.

**Comment by KiwiHawk** [comment]
Interesting idea! I'm definitely hesitant about it though. Getting anything for free is difficult to balance 😕 (Just look at prod modules!)

**Comment by Qatavin** [comment]
I think it would work if their production capabilities were like this:

SP1: 120 SPM
SP2: 100 SPM
SP3+4: 60 SPM
SP5+6: 50 SPM (production+logistic)
SP7: 30 SPM
SP8: 20 SPM
Space Age SPs: 20 SPM

That probably seems like a lot on its face, but it's really not. After all, in the early game you will have other things you need to craft by hand. And later on, all tech will require many different packs, so it's not like you can simply not set up some science packs... unless you plan things very carefully and skillfully, which, hey, is the whole point of this class, along with being able to snipe useful bonuses before you have the sci pack set up for them.

Is there a way to make certain recipes and technologies hidden unless at least one player is using a particular class?

**Comment by Qatavin** [comment]
I'm gonna put a pin on the Scientist question for... probably quite a while. I've thought of some methods using special unlock conditions to mitigate its problematic aspects, but testing them properly will take too long right now.
