### ISSUE TITLE
Bob's Greenhouse 2.0

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#248]
Greenhouse is another very simple one, but there are a couple questions to answer. First, I prepared some updated graphics for the greenhouse when I was developing my own mod's pinkhouse. Do we want to add them to this mod? Here's what they look like.

![greenhouse-update](https://github.com/user-attachments/assets/78fd908b-1114-4eec-bcff-e1b93552382f)
![greenhouse-1](https://github.com/user-attachments/assets/c534f53b-4b31-4459-b40a-7ae484f0ab62)

You can still see the central column from the lab when it's off. That can be painted out if desired, but I think this is fine as is.

I've also set up circuit connectors for the greenhouse. I'm not sure when they'd ever be used, but they exist now.

The second question is quality. Do we want to do something a little unusual and allow quality modules alone to be used in greenhouses to produce better wood?

**Comment by KiwiHawk** [comment]
Yes, those graphics look better. The current graphics pipe connection is broken on north rotation.

![image](https://github.com/user-attachments/assets/ea7a924f-cf43-4f43-98f9-562c149cdd22)

I'm not sure about Quality. I haven't had a chance to play through the expansion yet. Would this make it more of an overlap with the Space Age wood production?

**Comment by Qatavin** [comment]
SA wood production is planting trees on the map and then harvesting them, so there isn't an opportunity to get quality. At least, not directly. You can only use the recycler to try to level it up. That being the case, I suppose it would be best to not give greenhouses the ability to use quality, for consistency.
