### ISSUE TITLE
Bob tech 2.0 burner phase

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#256]
![Burner sci](https://github.com/user-attachments/assets/702cd8d9-f1f3-411c-9a37-8ecb7e361fb6)

I've gone over burner phase with an eye on the various changes made to vanilla, and this is what I think we should do with it. A few key points:

- Steam sci pack has been removed entirely, mostly replaced with item unlocks. I've always found that it was too simple and stopped being used too quickly to be satisfactory.
- As in AAI, steam engine 1 has been bumped down to require sci pack 2. This is really the only way to have a "burner power phase" last long enough to be meaningful. Otherwise, it's over and done with before you even notice it. As a consequence, steam engine 2 could potentially be unlocked very shortly after, but considering the amount of steel it needs, the cost (either in terms of amount of iron or amount of energy for electrolysing water) should make it a low priority upgrade.
- This doesn't work at all without a burner generator. The solution is to copy over the burner generator from Bob's Power to Bob's Tech.
- Steel has been bumped down the tree to also require sci pack 2. This barely makes a difference, though. Nearly all techs that need steel already require SP2. The only ones that don't are mining drill 2s, radar 2 (both of which now have a vanilla tier 1 tech that uses SP1, so bumping them and any subsequent upgrades down the tree by 1 science pack makes sense) and water miner 2 (which is a similar deal).

**Comment by KiwiHawk** [comment]
Yes, this makes sense to me. I assume it will include removing the burner lab. Seems pointless to keep that if the steam science pack is being removed.

**Comment by KiwiHawk** [comment]
### Issues with current burner phase implementation:

Tech loop. Lab tech depends on Automation Science pack which is unlocked by crafting a lab.
![image](https://github.com/user-attachments/assets/4b38c546-d024-4912-91aa-fa499bdb5d2e)

Steam engine is unlocked by both Electricity as well as Steam Power
![image](https://github.com/user-attachments/assets/d294b499-9f62-4694-9085-4c0610b0ea40)
![image](https://github.com/user-attachments/assets/b614ae56-d09a-459a-8066-ef1fce59eceb)
![image](https://github.com/user-attachments/assets/7f791b0e-abb5-497e-800a-26fe4ac85842)

Radar is unlock by both Radar and Electricity
![image](https://github.com/user-attachments/assets/56cecd70-efa6-4266-a556-6658f99b84ff)

**Comment by Qatavin** [comment]
Right. Various adjustments will have to be made, which haven't been applied yet. I think keeping the burner lab is the simpler option here, since electric labs will require basic electronics, but burner labs won't. If we do remove it, I guess we'd want to change basic electronics to unlock with copper wire? But doing that would mean crafting a bunch of power poles with nothing to power yet, so I don't think that's the most satisfactory way to go.
