### ISSUE TITLE
Hide Bob's Ores Settings

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#45]
MCI force enables required ores from Bob ores. Make MCI hide the settings for these ores as the settings don't do anything.

**Comment by Qatavin** [comment]
MCI force enabling all ores is also controlled by a setting - "Ore enable override". That would need to be hidden and force enabled as well.

**Comment by KiwiHawk** [comment]
Sulfur isn't being handled correctly.
